apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  better-auth-secret: {{ .Values.secrets.betterAuthSecret | quote }}
  resend-api-key: {{ .Values.secrets.resendApiKey | quote }}
