apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: backend
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: frontend
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notification
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: notification
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: notification
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-recurring
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: recurring
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: recurring
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-audit
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: audit
spec:
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
      name: http
  selector:
    app: audit
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
